{% set name = "aws-cdk.aws-cloudfront" %}
{% set version = "1.204.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.aws-cloudfront-{{ version }}.tar.gz
  sha256: dc7f348bdd752cac65e5c116c07a2ea9a587529792616268086f92c726d20212

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - aws-cdk.aws-certificatemanager ==1.204.0
    - aws-cdk.aws-cloudwatch ==1.204.0
    - aws-cdk.aws-ec2 ==1.204.0
    - aws-cdk.aws-iam ==1.204.0
    - aws-cdk.aws-kms ==1.204.0
    - aws-cdk.aws-lambda ==1.204.0
    - aws-cdk.aws-s3 ==1.204.0
    - aws-cdk.aws-ssm ==1.204.0
    - aws-cdk.core ==1.204.0
    - aws-cdk.cx-api ==1.204.0
    - constructs >=3.3.69,<4.0.0
    - python-jsii >=1.84.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.aws_cloudfront
    - aws_cdk.aws_cloudfront._jsii
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/aws-cdk
  summary: The CDK Construct Library for AWS::CloudFront
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
